repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: cmd /c "mamba activate deployable_scraper && pytest"
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        args: ["-v", "--tb=long", "tests/functionality_testing"]
      
      # - id: pytest-coverage
      #   name: pytest with coverage
      #   entry: pytest
      #   language: system
      #   types: [python]
      #   pass_filenames: false
      #   always_run: true
      #   args: ["--cov=src", "--cov-report=term-missing", "--cov-fail-under=80", "tests/"]