name: deployable_scraper
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - sqlite
  - pytest
  - schedule
  - pip:
      - pre-commit
      - APScheduler
      - git+https://github.com/NikolajMLund/scraping_charger_data.git
      - -e .
  